### ISSUE TITLE
Clarification on Class Handling and Background Processing

### ISSUE THREAD

**Issue by ChubbyPear** [CVIU-CSU/HRDecoder#1]
Hi! I hope you're doing well. I have a couple of questions regarding the class handling in your code.

    In lesion_dataset.py and hr_idrid_2880x1920-slide.py, the classes are defined as ['bg', 'EX', 'HE', 'SE', 'MA'], totaling 5 classes. However, in the decode_head configuration, num_classes is set to 4. Could you please explain the processing that leads to this difference?

    In the performance summary, the parameters related to bg are reported as NaN. How does the model handle the background region during training and evaluation?

Thank you for your assistance and for sharing your work!

**Comment by gitdzy** [comment]
Hello, thank you very much for your question. 

Actually, the model outputs 4 classes. This is in line with the setting in configs/_base_/models/hrdecoder_fcn_hr18.py, which is also 4. When we're dealing with loss calculation, only the classes 'EX', 'HE', 'SE', and 'MA' are used. The 'bg' class isn't part of this loss calculation process.

You have noticed that the 'bg' class shows up in the result summary. However, we don't actually calculate the metric for it. Because in the fundus lesion segmentation task, the majority of the area is background. Calculating the metric for the background does not make much sense. So we skip calculating its metric and that is why you see NaN in the result summary related to ‘bg’.

Dataset.CLASSES, defined as ['bg', 'EX', 'HE', 'SE', 'MA'] in configs/_base_/datasets/hr_idrid_2880x1920-slide.py, is mainly used in two specific parts of the code - when calculating the metric and for visualization purposes. 

In mmseg/datasets/lesion_dataset.py, the value of num_classes is 5, which is equal to len(['bg', 'EX', 'HE', 'SE', 'MA']).
![image](https://github.com/user-attachments/assets/be59eab9-8113-4b07-b743-ac64c45291b3)
But in mmseg/core/evaluation/lesion_metric.py, we skip the metric calculation for the 'bg' category.
![image](https://github.com/user-attachments/assets/ec97f7a8-d8e8-40b7-8388-d08da4141d5a)

And in mmseg/models/segmentors/base.py, we will perform visualization for the five categories ['bg', 'EX', 'HE', 'SE', 'MA'] based on their corresponding colors defined in Dataset.PALATTE.
![image](https://github.com/user-attachments/assets/9a5ec850-a471-4755-b0bc-eeec5ff0bf08)

So in fact, we add 'bg' to the classes and palattes defined in configs/_base_/datasets/hr_idrid_2880x1920-slide.py mainly for the visualization of the background category. 
I'm a bit sorry that this part of the code has caused your misunderstanding. I hope this answer is helpful to you.

**Comment by ChubbyPear** [comment]
Thank you for your patience and help! I still have some confusion:

Since the background isn't involved in the loss calculation and the decoder has num_classes=4, how does the model correctly identify and visualize the background during inference?

Actually, when trying to reproduce a similar work on a newer version of MMSeg, I set reduce_zero_label=True and num_classes=4. However, during inference, the model incorrectly classifies the background as one of the specific classes (from class 1 to 4). How can I address this issue to ensure the background is correctly identified?

Thank you again for your patience!

**Comment by ChubbyPear** [comment]
> Hello, thank you very much for your question.
> 
> Actually, the model outputs 4 classes. This is in line with the setting in configs/_base_/models/hrdecoder_fcn_hr18.py, which is also 4. When we're dealing with loss calculation, only the classes 'EX', 'HE', 'SE', and 'MA' are used. The 'bg' class isn't part of this loss calculation process.
> 
> You have noticed that the 'bg' class shows up in the result summary. However, we don't actually calculate the metric for it. Because in the fundus lesion segmentation task, the majority of the area is background. Calculating the metric for the background does not make much sense. So we skip calculating its metric and that is why you see NaN in the result summary related to ‘bg’.
> 
> Dataset.CLASSES, defined as ['bg', 'EX', 'HE', 'SE', 'MA'] in configs/_base_/datasets/hr_idrid_2880x1920-slide.py, is mainly used in two specific parts of the code - when calculating the metric and for visualization purposes.
> 
> In mmseg/datasets/lesion_dataset.py, the value of num_classes is 5, which is equal to len(['bg', 'EX', 'HE', 'SE', 'MA']). ![image](https://private-user-images.githubusercontent.com/91234876/385786718-be59eab9-8113-4b07-b743-ac64c45291b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjExNDcsIm5iZiI6MTczMTU2MDg0NywicGF0aCI6Ii85MTIzNDg3Ni8zODU3ODY3MTgtYmU1OWVhYjktODExMy00YjA3LWI3NDMtYWM2NGM0NTI5MWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA1MDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MWQzZDc2NzIxM2RjMDFmZDhhY2M3MDE3MmVlOWRlZjQxNTUwMjNjMDI3NjQyN2RhZjQ2ZGE2OTMyZTUwZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5IX8rsizDASvYZJCYo9GUuL69oEHhv0KmiBGzyCyWmw) But in mmseg/core/evaluation/lesion_metric.py, we skip the metric calculation for the 'bg' category. ![image](https://private-user-images.githubusercontent.com/91234876/385790565-ec97f7a8-d8e8-40b7-8388-d08da4141d5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjExNDcsIm5iZiI6MTczMTU2MDg0NywicGF0aCI6Ii85MTIzNDg3Ni8zODU3OTA1NjUtZWM5N2Y3YTgtZDhlOC00MGI3LTgzODgtZDA4ZGE0MTQxZDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA1MDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNGZiYWEyYzVjOWZmYzQ2YzBhMGNlMGQ2OGRmNDQ1OGFmZWNkNjY4YTk5Zjg3NzBkOTE2NGY4ZTA2YzE3NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pYJUCuAPMztz_e6-gx_YqkoGFJT9wlzr-qiyPlnh4xg)
> 
> And in mmseg/models/segmentors/base.py, we will perform visualization for the five categories ['bg', 'EX', 'HE', 'SE', 'MA'] based on their corresponding colors defined in Dataset.PALATTE. ![image](https://private-user-images.githubusercontent.com/91234876/385792194-9a5ec850-a471-4755-b0bc-eeec5ff0bf08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjExNDcsIm5iZiI6MTczMTU2MDg0NywicGF0aCI6Ii85MTIzNDg3Ni8zODU3OTIxOTQtOWE1ZWM4NTAtYTQ3MS00NzU1LWIwYmMtZWVlYzVmZjBiZjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA1MDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NGE2N2I4NDA4MmZmNWQyZjgyMzQ1NWZkNjY0ODJhMGNhYzc5M2E3OTc5YjgxZmZhOGI5N2FmYTFjOWFjODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c-7oycDWRgaEI2pIBCTGW0RNZWkcUiSRNEX89oCyPk0)
> 
> So in fact, we add 'bg' to the classes and palattes defined in configs/_base_/datasets/hr_idrid_2880x1920-slide.py mainly for the visualization of the background category. I'm a bit sorry that this part of the code has caused your misunderstanding. I hope this answer is helpful to you.

Thank you for your patience and help! I still have some confusion:

Since the background isn't involved in the loss calculation and the decoder has num_classes=4, how does the model correctly identify and visualize the background during inference?

Actually, when trying to reproduce a similar work on a newer version of MMSeg, I set reduce_zero_label=True and num_classes=4. However, during inference, the model incorrectly classifies the background as one of the specific classes (from class 1 to 4). How can I address this issue to ensure the background is correctly identified?

Thank you again for your patience!

**Comment by gitdzy** [comment]
I remember I've encountered a similar issue before. 

We assume that the 0th category is the background when we set reduce_zero_label=True. Then when calculating the metric, since the background needs to be removed, 0 is set to 255.
![image](https://github.com/user-attachments/assets/411c54b5-218a-4f40-b416-b67b8243e560)

If you want to ensure that the background category can be correctly identified during inference, setting reduce_zero_label=False and num_classes=4 should work.

Or maybe you can implement a metric function by yourself like I did. This way, the background category can also be correctly identified.

**Comment by ChubbyPear** [comment]
> I remember I've encountered a similar issue before.
> 
> We assume that the 0th category is the background when we set reduce_zero_label=True. Then when calculating the metric, since the background needs to be removed, 0 is set to 255. ![image](https://private-user-images.githubusercontent.com/91234876/388062951-411c54b5-218a-4f40-b416-b67b8243e560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzc2MzYsIm5iZiI6MTczMjE3NzMzNiwicGF0aCI6Ii85MTIzNDg3Ni8zODgwNjI5NTEtNDExYzU0YjUtMjE4YS00ZjQwLWI0MTYtYjY3YjgyNDNlNTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA4MjIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiOGIzMmU3ZjNlNmFhZDU0ZmM2OGE1MmIwYTIzNmUwMmY2Nzc3N2EwMjNkYmE4MmNkZTk1MmZlYzk1YTc3YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z-nJg0DboJTECqRT3SDJxjnK7cfDcpk-xM8YsTXvvHw)
> 
> If you want to ensure that the background category can be correctly identified during inference, setting reduce_zero_label=False and num_classes=4 should work.
> 
> Or maybe you can implement a metric function by yourself like I did. This way, the background category can also be correctly identified.

Thank you for your patient response. I redesigned my metric based on your code, and my issue is resolved.
HRDecoder is an excellent work with impressive performance. I've learned a lot from it. Thank you for your contribution!

**Comment by wk19990213** [comment]
![image](https://github.com/user-attachments/assets/34c043b8-d843-4c71-ae15-bbe4dc011e33)


你好，我在复现代码时，程序报错在Utils下找不到SelfAttentionBlock这个模块，有些疑惑，希望能得到解答，十分感谢
